title: Project

columns:
  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          typology:
            label: Typology
            type: text
            width: 1/2
            icon: tag
            required: true
          plotArea:
            label: Plot Area
            type: text
            width: 1/2
            icon: square
            required: true
          builtArea:
            label: Built Up Area
            type: text
            width: 1/2
            icon: circle
            required: true
          levels:
            label: Levels
            type: text
            width: 1/2
            icon: number
          location:
            label: Location
            type: text
            icon: location
          text:
            label: Text
            type: textarea
            help: Introduction to the project
            icon: text

  - width: 1/2
    sections:
      gallery:
        headline: Project Images
        type: files
        layout: cards
        template: gallery-image
        info: "{{ file.summary }} / {{ file.alt }} / {{ file.dimensions }}"
        image:
          ratio: 1/1
          cover: true
