title: Project

columns:
  - width: 1/5
    sections:
      image:
        type: files
        headline: Cover Image
        help: Upload image titled 'cover' to make it the project cover.
        template: cover-image
        max: 1
        layout: cards
        info: "{{ file.alt }} / {{ file.dimensions }}"
        image:
          ratio: 4/3
          cover: true

  - width: 1/2
    sections:
      info:
        type: fields
        fields:
          icon:
            label: Icon
            type: files
            help: Upload file named 'icon' – should have 100x100 dimension, preferably .png or .ico filetype.
            max: 1
            layout: cards
            info: "{{ file.dimensions }}"
            image:
              ratio: 1/1
              cover: true
          typology:
            label: Typology
            type: select
            options:
              Architecture Residential: Architecture Residential
              Architecture Commercial: Architecture Commercial
              Architecture Residential cum Commercial: Architecture Residential cum Commercial
              Master Planning: Master Planning
              Interior Residential: Interior Residential
              Interior Commercial: Interior Commercial
              Interior Lobbies: Interior Lobbies
              Interior Clubhouse: Interior Clubhouse
              Landscape: Landscape
              Residential & Club: Residential & Club
            icon: tag
            required: true
          year:
            label: Design & Construction
            type: text
            icon: clock
          projectStatus:
            label: Status
            type: select
            options:
              Ongoing: Ongoing
              Completed: Completed
              Upcoming: Upcoming
          plotArea:
            label: Plot Area
            type: text
            width: 1/2
            icon: square
            required: true
          builtArea:
            label: Built Up Area
            type: text
            width: 1/2
            icon: circle
            required: true
          levels:
            label: Levels
            type: text
            width: 1/2
            icon: number
          location:
            label: Location
            type: text
            icon: location
          developer:
            label: Developer
            type: text
            icon: person
          text:
            label: Summary
            type: textarea
            help: Short introduction to the project
            icon: text
            size: large

  - width: 1/2
    sections:
      gallery:
        headline: Project Images
        type: files
        layout: cards
        template: gallery-image
        info: "{{ file.alt }} / {{ file.dimensions }}"
        image:
          ratio: 1/1
          cover: true


